# Regenerates technical documentation for repository scripts.
[CmdletBinding()]
param(
    [string]$RepositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
)

$ErrorActionPreference = 'Stop'

$registryPath = Join-Path $RepositoryRoot 'docs\SCRIPT_REGISTRY.md'
$scriptFiles = Get-ChildItem -Path $RepositoryRoot -Recurse -File -Include *.ps1,*.psm1,*.psd1,*.sh |
    Where-Object {
        $_.FullName -notmatch '\\.git\\' -and
        $_.FullName -notmatch '\\node_modules\\' -and
        $_.FullName -notmatch '\\.next\\'
    } |
    Sort-Object FullName

$generatedAt = (Get-Date).ToString('yyyy-MM-dd HH:mm:ss zzz')
$lines = New-Object System.Collections.Generic.List[string]

$lines.Add('# Script Registry')
$lines.Add('')
$lines.Add('Generated by `docs/update-script-registry.ps1`. Do not edit this file manually.')
$lines.Add('')
$lines.Add("Last generated: $generatedAt")
$lines.Add('')
$lines.Add('| Script | Size | SHA256 | Purpose |')
$lines.Add('|---|---:|---|---|')

foreach ($file in $scriptFiles) {
    $rootWithSeparator = $RepositoryRoot.TrimEnd('\') + '\'
    $relativePath = $file.FullName.Substring($rootWithSeparator.Length).Replace('\', '/')
    $hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $file.FullName).Hash.ToLowerInvariant()
    $firstPurposeLine = Get-Content -LiteralPath $file.FullName -TotalCount 8 |
        Where-Object { $_ -match '^\s*#\s+.+' } |
        Select-Object -First 1

    $purpose = if ($firstPurposeLine) {
        ($firstPurposeLine -replace '^\s*#\s*', '').Trim()
    }
    else {
        'No purpose comment found.'
    }

    $lines.Add("| ``$relativePath`` | $($file.Length) bytes | ``$hash`` | $purpose |")
}

if ($scriptFiles.Count -eq 0) {
    $lines.Add('| _No scripts found_ | 0 bytes | n/a | Add scripts under `docs/` or project automation folders. |')
}

Set-Content -LiteralPath $registryPath -Value $lines -Encoding UTF8
Write-Host "Updated $registryPath"
